//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группа_ВремяНачала
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группа_ВремяНачала()
        {
            this.ВремяНачала = new HashSet<ВремяНачала>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public Nullable<int> Значение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВремяНачала> ВремяНачала { get; set; }
    }
}
