//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Описание_MOOC
    {
        public int id { get; set; }
        public string URL { get; set; }
        public string НазваниеКурса { get; set; }
        public int Провайдер { get; set; }
        public string Институт { get; set; }
        public Nullable<int> ПредметнаяОбласть { get; set; }
        public Nullable<int> ВремяНачала { get; set; }
        public Nullable<bool> НаличиеСертификата { get; set; }
        public Nullable<bool> Школа { get; set; }
        public Nullable<bool> ВысшееОбразование { get; set; }
        public Nullable<bool> ПовышениеКвалификации { get; set; }
    
        public virtual ВремяНачала ВремяНачала1 { get; set; }
        public virtual ПредметнаяОбласть ПредметнаяОбласть1 { get; set; }
        public virtual Провайдер Провайдер1 { get; set; }
    }
}
