//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредметнаяОбласть
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПредметнаяОбласть()
        {
            this.Описание_MOOC = new HashSet<Описание_MOOC>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public Nullable<int> Группа { get; set; }
    
        public virtual Группа_ПредметнаяОбласть Группа_ПредметнаяОбласть { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Описание_MOOC> Описание_MOOC { get; set; }
    }
}
